#!/bin/bash
exit 0 # Comment out to enable ctags
set -e
dir="$(git rev-parse --git-dir)"
mkdir "$dir/tags_lock" 2>/dev/null || exit 0
trap 'rmdir "$dir/tags_lock"; rm -f "$dir/tags.$$"' EXIT INT TERM
git ls-files | ctags --tag-relative -L- -f.git/tags.$$ --languages=-sql
mv "$dir/tags.$$" "$dir/tags"
