* Dotfiles

These are my dotfiles. There are many like them, but these ones are mine. I take
my dotfiles very seriously, as any professional programmer should.

For the time being, I'm using ~git~ to track my configurations across multiple
hosts using branches. These branches has a set of host-specific patches which
are continuously rebased on top of the master branch. This provides a sensible
backup across hosts, while having tailored configuration for each host.

Most configurations are applied by symlinking dotfiles into ~$HOME~ using [[https://www.gnu.org/software/stow/][GNU stow]].

** Installation

#+BEGIN_SRC sh
stow --target=$HOME <dir>
#+END_SRC

I'm mostly using a tiny bash wrapper around stow:

#+BEGIN_SRC sh
$ ./install <emacs|git|zsh|...>
#+END_SRC

see:

#+BEGIN_SRC sh
$ ./install -h
#+END_SRC

** Submodules

I'm using ~git submodules~ to track some external dependencies like [[https://github.com/myme/doom-emacs][Doom Emacs]],
[[https://github.com/myme/prezto][Prezto]], [[https://github.com/junegunn/fzf.git][fzf]] (NB: some are personal forks of awesome upstream software, so please
check out the origin).

** Issues :noexport:

*** DNS resolve                                                         :dns:

Ref this answer, multi-case DNS may cause issues: [[http://askubuntu.com/questions/81797/nslookup-finds-ip-but-ping-doesnt][nslookup finds ip, but ping doesnt]]

In [[file:/etc/nsswitch.conf::#%20hosts:%20files%20mdns4_minimal%20%5BNOTFOUND=return%5D%20resolve%20%5B!UNAVAIL=return%5D%20dns][nsswitch.conf]], change the following:

#+BEGIN_SRC diff
- hosts:          files mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns
+ hosts:          files dns
#+END_SRC

or remove completely:

#+BEGIN_SRC sh
$ sudo apt remove libnss-mdns
#+END_SRC

*** ZSH 5.2 has a broken function in `VCS_INFO_nvcsformats`             :zsh:

#+BEGIN_SRC sh
## vim:ft=zsh
## Written by Frank Terbeck <ft@bewatermyfriend.org>
## Distributed under the same BSD-ish license as zsh itself.

setopt localoptions noksharrays NO_shwordsplit
local c v rr
local -a msgs ### <-- NB: Comment out this line

if [[ $1 == '-preinit-' ]] ; then
    c='default'
    v='-preinit-'
    rr='-all-'
fi
zstyle -a ":vcs_info:${v:-$vcs}:${c:-$usercontext}:${rrn:-$rr}" nvcsformats msgs
(( ${#msgs} > maxexports )) && msgs[${maxexports},-1]=()
return 0
```

Comment out the line as mentioned in the script above to get paths in the prompt working.



#+END_SRC
